---
title: "R Notebook"
output: html_notebook
---

```{r}
# read in clinical and genomic data of patients
library(readr)
# cli_dat = read_tsv("E:/Lab/COMP562/proj/tmb_mskcc_2018/data_clinical_sample.txt", skip = 4)
# cli_dat = cli_dat[c("PATIENT_ID", "SAMPLE_ID", "CANCER_TYPE", "AGE_AT_SEQ_REPORT", "TMB_NONSYNONYMOUS")]
data <- read_csv("E:/Lab/MSK/project/data/220627_ICI_genomics_clinical/062722_CutaneousMelanoma_ICI_1stLine_Genomics.csv")
data
```
```{r}
# read in clinical and genomic data of patients
library(readr)
cli_dat = read_tsv("E:/Lab/COMP562/proj/tmb_mskcc_2018/data_clinical_sample.txt", skip = 4)
# merge clinical and genomic data
gen_dat = read_tsv("E:/Lab/COMP562/proj/tmb_mskcc_2018/data_mutations.txt")
cli_gen_dat = merge(gen_dat, cli_dat, by.x = 'Tumor_Sample_Barcode', by.y ='SAMPLE_ID', all= TRUE)
# add patient data (survival and sex)
sur_dat = read_tsv("E:/Lab/COMP562/proj/tmb_mskcc_2018/data_clinical_patient.txt", skip=4)
final_dat = merge(sur_dat, cli_gen_dat, by="PATIENT_ID")
final_dat
```

```{r}
# cancer type subsetting
lung_dat = subset(final_dat, final_dat$CANCER_TYPE=="Non-Small Cell Lung Cancer")
skin_dat = subset(final_dat, final_dat$CANCER_TYPE=="Melanoma")
blad_dat = subset(final_dat, final_dat$CANCER_TYPE=="Bladder Cancer")
rcc_dat = subset(final_dat, final_dat$CANCER_TYPE=="Renal Cell Carcinoma")
# laml conversion
library(maftools)
laml = read.maf(maf = final_dat, clinicalData = final_dat)
laml_lung = read.maf(maf = lung_dat, clinicalData = lung_dat)
laml_skin = read.maf(maf = skin_dat, clinicalData = skin_dat)
laml_blad = read.maf(maf = blad_dat, clinicalData = blad_dat)
laml_rcc = read.maf(maf = rcc_dat, clinicalData = rcc_dat)
```

```{r}
fab.ce = clinicalEnrichment(maf = laml, clinicalFeature = 'OS_STATUS')
ce = fab.ce$groupwise_comparision[p_value < 0.05]
ce_genes = unique(ce$Hugo_Symbol)
ce_genes
```
```{r}
# lung
fab.ce = clinicalEnrichment(maf = laml_lung, clinicalFeature = 'OS_STATUS')
ce = fab.ce$groupwise_comparision[p_value < 0.05]
unique(ce$Hugo_Symbol)
```

```{r}
# skin
fab.ce = clinicalEnrichment(maf = laml_skin, clinicalFeature = 'OS_STATUS')
ce = fab.ce$groupwise_comparision[p_value < 0.05]
unique(ce$Hugo_Symbol)
```


```{r}
# bladder
fab.ce = clinicalEnrichment(maf = laml_blad, clinicalFeature = 'OS_STATUS')
ce = fab.ce$groupwise_comparision[p_value < 0.05]
unique(ce$Hugo_Symbol)
```

```{r}
# rcc
fab.ce = clinicalEnrichment(maf = laml_rcc, clinicalFeature = 'OS_STATUS')
ce = fab.ce$groupwise_comparision[p_value < 0.05]
unique(ce$Hugo_Symbol)
```
```

